name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
          add-tools-to-path: true
          cache: true

      - name: Install jom
        id: jom-setup
        shell: pwsh
        run: |
          $url = "https://download.qt.io/official_releases/jom/jom_1_1_4.zip"
          $outputPath = "jom_1_1_4.zip"
          Invoke-WebRequest -Uri $url -OutFile $outputPath
          $extractPath = "jom"
          if (-not (Test-Path $extractPath)) {
            New-Item -ItemType Directory -Path $extractPath | Out-Null
          }
          Expand-Archive -Path $outputPath -DestinationPath $extractPath
          $jomDir = "$(pwd)\jom"
          $jomExe = "$jomDir\jom.exe"
          if (Test-Path $jomExe) {
            Write-Output "JOM Path: $jomDir"
            Write-Output "::set-output name=jom_path::$jomDir"
          } else {
            Write-Error "jom.exe not found in $jomDir"
            exit 1
          }

      - name: Build with qmake and jom
        shell: pwsh
        run: |
          mkdir build
          cd build
          qmake ..\Qwote.pro CONFIG+=release
          $jomPath = "${{ steps.jom-setup.outputs.jom_path }}"
          & "$jomPath\jom.exe"
          
      - name: Remove source and object files
        shell: pwsh
        run: |
          $buildDir = "build/release"
          if (Test-Path $buildDir) {
              Get-ChildItem -Path $buildDir -Include *.cpp, *.h, *.obj, *.res, *.qrc, *.qm -Recurse | Remove-Item -Force
          } else {
              Write-Host "Directory not found: $buildDir"
          }

      - name: Deploy Qt
        shell: pwsh
        run: |
          cd build
          $windeployqtPath = "D:\a\Qwote\Qt\6.7.2\msvc2019_64\bin\windeployqt6.exe"
          if (Test-Path $windeployqtPath) {
              & $windeployqtPath `
                  --exclude-plugins qsvgicon,qsvg,qico,qjpeg,qgif,qnetworklistmanager,qtuiotouchplugin `
                  --no-opengl-sw `
                  --no-system-dxc-compiler `
                  --no-compiler-runtime `
                  --no-translations `
                  --no-system-d3d-compiler `
                  D:\a\Qwote\Qwote\build\release\Qwote.exe
          } else {
              Write-Error "windeployqt not found at the expected path!"
              exit 1
          }

      - name: Rename release folder
        shell: pwsh
        run: |
          $releaseDir = "build/release"
          $newDir = "Qwote"
          if (Test-Path $releaseDir) {
              Rename-Item -Path $releaseDir -NewName $newDir
          } else {
              Write-Error "Release folder not found!"
              exit 1
          }

      - name: Zip binaries folder
        shell: pwsh
        run: |
          $zipFile = "build/Qwote_msvc_64.zip"
          $folder = "build/Qwote"
          Compress-Archive -Path $folder -DestinationPath $zipFile

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Qwote_msvc_64
          path: build/Qwote_msvc_64.zip

  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.4.2'
          host: 'linux'
          add-tools-to-path: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev

      - name: Build with qmake
        run: |
          mkdir build
          cd build
          qmake ../HeadsetControl-Qt.pro CONFIG+=release
          make -j$(nproc)

      - name: Zip binaries folder
        run: |
          zip build/HeadsetControl-Qt_linux_64.zip build/HeadsetControl-Qt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HeadsetControl-Qt_linux_64
          path: build/HeadsetControl-Qt_linux_64.zip